# Generated by Django 5.0.3 on 2024-09-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': [('can_view_news', 'Can view news'), ('can_edit_news', 'Can edit news'), ('can_delete_news', 'Can delete news')], 'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Taglar'},
        ),
    ]
